/*
 * Copyright (c) 2025 GentleCare Corporation. All rights reserved.
 *
 * This source code and the accompanying materials are the confidential and
 * proprietary information of GentleCare Corporation. Unauthorized copying or
 * distribution of this file, via any medium, is strictly prohibited without
 * the prior written permission of GentleCare Corporation.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#pragma once

#if PLATFORM_TYPE == 0

#define DEVICE_NAME "GentleWedge"
#define ADVERTISED_NAME "Wedge"

#define PRESSURE_SENSOR_SCL_PIN 13
#define PRESSURE_SENSOR_SDA_PIN 14

#define ENABLE_MOTOR_CONTROLLER 1
#define MOTOR_CONTROLLER_RX_PIN 16
#define MOTOR_CONTROLLER_TX_PIN 17
#define TORQUE_CONSTANT -7.4439
#define GEARBOX_RATIO 81.0

#define VOLTAGE_DIMMER_PWM_PIN 18
#define VOLTAGE_DIMMER_LEDC_CHANNEL 0
#define MAX_DIMMER_VOLTAGE 120.0

#define ENABLE_SERVO 1
#define SERVO_PWM_PIN 19
#define SERVO_LEDC_CHANNEL 1
#define SERVO_ANGLE1 128.0
#define SERVO_ANGLE2 48.0
// #define SERVO_ANGLE1 4.0
// #define SERVO_ANGLE2 124.0

#define LEFT_VALVE_PIN 32
#define RIGHT_VALVE_PIN 27
#define VALVE_DIGITAL_PIN1 25
#define VALVE_DIGITAL_PIN2 26
#define RAIL_STATE_PIN 35
#define BOX_TO_RAIL_PIN 33


#define ENABLE_CONTROL_PANEL 0

#define REFERENCE_TORQUE 0.0
#define SHEET_LENGTH 12.0
#define PRESSURE_LIMIT 3.0
#define TORQUE_LIMIT 7.0
#define EVERSION_PAUSED_VOLTAGE 40.0
#define BASE_VOLTAGE 50.0
#define BASE_SPEED 10.0
#define INVERSION_PRESSURE 0.25
#define INVERSION_VOLTAGE 48.0
#define BUMPER_INVERSION_VOLTAGE 0.0
#define BUMPER_PAUSED_VOLTAGE 0.0
#define INVERSION_PAUSED_VOLTAGE 30.0
#define EVERSION_MIN_VOLTAGE 30.0
#define EVERSION_MAX_VOLTAGE 120.0
#define BUMPER_MIN_VOLTAGE 0.0
#define BUMPER_MAX_VOLTAGE 60.0


#elif PLATFORM_TYPE == 1

#define DEVICE_NAME "GentleGlide"
#define ADVERTISED_NAME "Glide"

#define ENABLE_MOTOR_CONTROLLER 1
#define MOTOR_CONTROLLER_RX_PIN 16
#define MOTOR_CONTROLLER_TX_PIN 17
#define TORQUE_CONSTANT -7.4439
#define GEARBOX_RATIO 81.0

#define VOLTAGE_DIMMER_PWM_PIN 18
#define VOLTAGE_DIMMER_LEDC_CHANNEL 0
#define MAX_DIMMER_VOLTAGE 120.0
#define VOLTAGE_DIMMER2_PWM_PIN 5
#define VOLTAGE_DIMMER2_LEDC_CHANNEL 3

#define LEFT_VALVE_PIN 25
#define RIGHT_VALVE_PIN 26
#define RAIL_STATE_PIN -1
#define BOX_TO_RAIL_PIN -1

#define ENABLE_SERVO 0
#define SERVO_PWM_PIN 19
#define SERVO_LEDC_CHANNEL 1
#define SERVO_ANGLE1 0.0
#define SERVO_ANGLE2 179.0

#define ENABLE_CONTROL_PANEL 0

#define REFERENCE_TORQUE 1.25
#define SHEET_LENGTH 26
#define PRESSURE_LIMIT 1.0
#define TORQUE_LIMIT 7.0
#define EVERSION_PAUSED_VOLTAGE 40.0
#define BASE_VOLTAGE 50.0
#define BASE_SPEED 30.0
#define INVERSION_PRESSURE 1.0
#define INVERSION_VOLTAGE 75 //37.0
#define BUMPER_INVERSION_VOLTAGE 20.0
#define BUMPER_PAUSED_VOLTAGE 30.0
#define INVERSION_PAUSED_VOLTAGE 30.0
#define EVERSION_MIN_VOLTAGE 30.0
#define EVERSION_MAX_VOLTAGE 120.0
#define BUMPER_MIN_VOLTAGE 0.0
#define BUMPER_MAX_VOLTAGE 60.0

#else

#error "Unknown platform type"

#endif