; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = wedge_v1

[platform_base]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 460800
build_flags = 
	-I ../
	-D BAUD_RATE=115200
lib_deps = 
	h2zero/NimBLE-Arduino@^2.3.6
	adafruit/Adafruit SSD1306@^2.5.15
	adafruit/Adafruit MPRLS Library@^1.2.2
	sparkfun/SparkFun LPS28DFW Arduino Library@^1.0.0
	solderedelectronics/Soldered CAN Bus Breakout Arduino Library@^1.1.1
	pierremolinaro/ACAN2517FD@^2.1.16
	mjbots/Moteus@^1.1.2

[env:wedge_v0]
extends = platform_base
build_flags = 
	${platform_base.build_flags}
	-D WEDGE_V0
	-D SHEET_W0
	-D MOTOR_TYPE_81
	-D PLATFORM_TYPE=0
	-D SOFTWARE_VERSION=0


[env:wedge_v1]
extends = platform_base
build_flags = 
	${platform_base.build_flags}
	-D WEDGE_V1
	-D SHEET_W0
	-D MOTOR_TYPE_MOTEUS
	-D BAUD_RATE=460800
	-D PLATFORM_TYPE=0
	-D SOFTWARE_VERSION=1

[env:glide_v0]
extends = platform_base
build_flags = 
	${platform_base.build_flags}
	-D GLIDE_V0
	-D SHEET_G0
	-D MOTOR_TYPE_81
	-D PLATFORM_TYPE=1
	-D SOFTWARE_VERSION=0

[env:glide_v1]
extends = platform_base
build_flags = 
	${platform_base.build_flags}
	-D GLIDE_V1
	-D SHEET_G1
	-D MOTOR_TYPE_53
	-D PLATFORM_TYPE=1
	-D SOFTWARE_VERSION=0

[env:glide_v2]
extends = platform_base
build_flags = 
	${platform_base.build_flags}
	-D GLIDE_V2
	-D SHEET_G2
	-D PLATFORM_TYPE=1
	-D SOFTWARE_VERSION=1
